services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.prod
    hostname: Ubuntu-2404-noble-amd64-base
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /root/Audio_Separation_Pipeline/Media/Filmes_Entrada:/app/Media/Filmes_Entrada
      - /root/Audio_Separation_Pipeline/Media/Filmes_Saida:/app/Media/Filmes_Saida
      - /root/Audio_Separation_Pipeline/logs:/app/logs
      - /root/Audio_Separation_Pipeline/tmp:/app/tmp
      - /root/.ssh:/root/.ssh:ro
      - /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
